definitions:
  handlers.AuthBody:
    properties:
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  handlers.RegisterBody:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Позволяет пользователю войти в систему, проверяя имя пользователя
        и пароль
      parameters:
      - description: Данные для входа
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.AuthBody'
      produces:
      - application/json
      responses:
        "200":
          description: Токен успешной авторизации
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный ввод
          schema:
            type: string
        "401":
          description: Неверное имя пользователя или пароль
          schema:
            type: string
        "500":
          description: Ошибка генерации токена
          schema:
            type: string
      summary: Авторизация пользователя
      tags:
      - Auth
  /api/register:
    post:
      consumes:
      - application/json
      description: Регистрирует пользователя в системе, проверяя имя пользователя
        и пароль
      parameters:
      - description: Данные для входа
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterBody'
      produces:
      - application/json
      responses:
        "201":
          description: Пользователь успешно зарегистрирован
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный ввод
          schema:
            type: string
        "500":
          description: Ошибка генерации пароля
          schema:
            type: string
        "503":
          description: Серверная ошибка регистрация пользователя
          schema:
            type: string
      summary: Регистрация пользователя
      tags:
      - Register
swagger: "2.0"
